---
name: Nicolas
surname: Mathias Hahn
position: ""
address: |
         | Av. Protásio Alves - Rio Branco - Porto Alegre - RS - Brasil
phone: +55 51 9 9191 3727
email: "nicolasmahahn@gmail.com"
github: nmhahn
linkedin: nmhahn
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: | 
         | Sou um profissional com formação em Estatística e atuo como Cientista de Dados. Sendo assim, busco aprimorar minhas hard skills (estatística, machine learning, modelagem) e soft skills (comunicação, resiliência, autogestão), me desenvolvendo continuamente. 
         | Além disso, estou construindo minha carreira na área de Dados.
headcolor: 126aa1
output: 
  vitae::awesomecv:
    keep_tex: false
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(vitae)      # The CV's LaTeX Template
library(tibble)     # Data sctructure for tribbles
library(magrittr)   # The Pipe %>%
library(here)       # Relative Filepaths
library(readr)      # Data Loading

options(encoding = 'UTF-8')
source(file = here('CV','data-ptBR.R'))
```


# Educação
```{r EDUCAÇÃO, echo=FALSE}
edu %>%
  detailed_entries(
    with = formacao,
    what = instituicao,
    why = detalhe,
    when = glue::glue('{inicio} - {fim}',.na = '')
  )
```

# Experiência
```{r EXPERIÊNCIA, echo=FALSE}
experiencia %>%
  detailed_entries(
    with = cargo,
    what = empresa,
    why = detalhe,
    when = glue::glue('{inicio_mes} {inicio_ano} - {fim_mes} {fim_ano}',.na = '')
  )
```

\newpage
# Habilidades
```{r HABILIDADES, echo=FALSE}
habilidades %>%
  detailed_entries(
    with = area,
    what = habilidades
  )
```

# Treinamentos | Cursos | Certificações
```{r CURSOS, echo=FALSE}
cursos %>%
  detailed_entries(
    with = curso,
    what = instituicao,
    why = detalhe,
    when = glue::glue('{mes} {ano}',.na = '')
  )
```

\newpage
# Eventos
```{r EVENTOS, echo=FALSE}
eventos %>%
  detailed_entries(
    with = evento,
    what = instituicao,
    why = detalhe,
    when = glue::glue('{mes} {ano}',.na = '')
  )
```

# Hobbies
```{r HOBBIES, echo=FALSE}
hobbies %>%
  detailed_entries(
    with = hobby,
    what = detalhe
  )
```
